### ISSUE TITLE
Code for Disentanglement-Transformation (DT) curve

### ISSUE THREAD

**Issue by itsnickchiu** [yxuhan/IALS#5]
Hi,

Thanks for your excellent work!
Could you release the code for calculating Disentanglement-Transformation (DT) curve?
The metric would be very useful for calculating disentanglement between different attributes and helpful for comparison with different image editing methods.

**Comment by yxuhan** [comment]
Hi, I'm working towards the deadline of SIGGRAPH Asia (5.24) now for another project, so I have no time to clean up and release the code before that time. If you still need the DT-curve code, please contact me (hanyx22@mails.tsinghua.edu.cn) after 5.24 and I will spend some time finding and releasing that code.

**Comment by yxuhan** [comment]
The code is released now. See [here](https://github.com/yxuhan/IALS/tree/main/dt_score).
