### ISSUE TITLE
How to train a classifier for hair style

### ISSUE THREAD

**Issue by dinusha94** [yxuhan/IALS#6]
Hi can you provide How can I add a new attribute by creating a new classifier for hairstyle

Thank you

**Comment by yxuhan** [comment]
Hi @dinusha94, take bald as an example, you can train a classifier using the dataset provided by [HairMapper: Removing Hair from Portraits Using GANs](https://onethousandwu.com/publication/hair_mapper_cvpr2022) as the label bald, and random images sampled from FFHQ as the label non-bald.
